Algoritmo "semnome"








Var
nome: caractere
nota1: real
nota2: real
nota3: real
media: real





Inicio


Escreval("Qual seu nome ?")
Leia(Nome)
escreval("Qual sua Primira Nota ?")
leia(nota1)
Escreval("Qual sua Segunda Nota ?")
leia(nota2)
Escreval("Qual sua terceira nota ?")
leia(nota3)

media <- (nota1 + nota2 + nota3) /3

Escreval(">----Parabens----<")
Escreval("Aluno: ",nome)
escreval("Sua nota é: ",media)




Fimalgoritmo