Algoritmo "semnome"






Var
nome: caractere
Idade: inteiro
Salario: real



Inicio

escreval("Qual seu nome ?")
leia (nome)
escreval ("Qual Sua Idade ?")
leia (Idade)
Escreval ("Qual seu Salario?")
Leia(Salario)



Escreval("--- DADOS CADASTRADOS ---")
Escreval("     Seu Nome é: ",nome)
Escreval("     Sua idade é: ",idade)
EscrevaL("     Seu salario é: ",Salario)


Fimalgoritmo